script : [chunk join] chunk

chunk : [(sentence pipe)+] sentence

sentence : command [" "+ option] [(" "+ arg)+] [/\n+/]

command : chars
        | ([chars] subshell [chars])+
option : "-" (chars|subshell)+
arg : chars [(" " chars)+]
    | "'" allchars "'"
    | ([chars] subshell [chars])+

subshell : "(" script ")" [/\n+/]

chars : /[^\+\|\s\(\)-']+/[/\n+/]
allchars : /[^']+/[/\n+/]
join : [" "+] "+" [" "+]
pipe : [" "+] "|" [" "+]